version: '3.5'
services:
  web:
    image: nginx:1.16
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./packages/infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.infra/nginx/logs/:/var/log/nginx/
      - ./.infra/nginx/cache/:/var/cache/nginx/
  mongo:
    container_name: mzm-mongo
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.infra/mongo/mongod.conf:/etc/mongod.conf
      - ./.infra/mongo/db:/data/db
      - ./.infra/mongo/configdb:/data/configdb
  mongo-test:
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:6
    ports:
      - 6379:6379
  redis-test:
    image: redis:6
    ports:
      - 6380:6379
  elasticsearch:
    build:
      context: ./packages/infra/elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200