name: test socket

on:
  push:
    paths:
      - 'packages/socket/**'
      - 'packages/shared/**'
      - 'packages/package.json'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/socket/**'
      - 'packages/shared/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build -w packages/socket
      - run: npm run test -w packages/socket
        env:
          CI: true
      - name: test docker build
        uses: docker/build-push-action@v2
        with:
          file: packages/socket/Dockerfile
          context: .
          push: false
