name: test backend

on:
  push:
    paths:
      - 'packages/backend/**'
      - 'packages/shared/**'
      - 'packages/package.json'
  pull_request:
    paths:
      - 'packages/backend/**'
      - 'packages/shared/**'

env:
  WORKSPACE_NAME: mzm-backend

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5
        command: --replSet rs0 --bind_ip_all
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.hello().ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30

    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - uses: ./.github/actions/initialize-mongodb-replica-set
        with:
          working-directory: packages/backend
      - run: npx concurrently "npm run build -w ${{ env.WORKSPACE_NAME }}" "npm run lint -w ${{ env.WORKSPACE_NAME }}" "npm run build:test -w ${{ env.WORKSPACE_NAME }}"
      - run: npm run test:ci -w ${{ env.WORKSPACE_NAME }}
        env:
          CI: true
          TEST_MONGODB_PORT: 27017
      - name: test docker build
        uses: docker/build-push-action@v6
        with:
          file: packages/backend/Dockerfile
          context: .
          push: false
