name: mzm-socket

on:
  push:
    paths:
      - 'packages/socket/**'
    branches: [ master ]
  pull_request:
    paths:
      - 'packages/socket/**'
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci -w packages/socket
      - run: npm run build -w packages/socket
      - run: npm run test -w packages/socket
        env:
          CI: true
