name: test shared

on:
  push:
    paths:
      - 'packages/shared/**'
      - 'packages/package.json'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/shared/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build -w packages/shared
      - run: npm run test -w packages/shared
        env:
          CI: true