name: test auth

on:
  push:
    paths:
      - 'packages/auth/**'
      - 'packages/shared/**'
      - 'packages/package.json'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/auth/**'
      - 'packages/shared/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build -w packages/auth
      - run: npm run test -w packages/auth
        env:
          CI: true
      - name: test docker build
        uses: docker/build-push-action@v2
        with:
          file: packages/auth/Dockerfile
          context: .
          push: false
