name: test frontend

on:
  push:
    paths:
      - 'packages/frontend/**'
      - 'packages/shared/**'
      - 'packages/package.json'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/frontend/**'
      - 'packages/shared/**'
    branches: [ main ]

env:
  WORKSPACE_NAME: mzm-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build -w ${{ env.WORKSPACE_NAME }}
      - run: npm run build:tsc -w ${{ env.WORKSPACE_NAME }}
      - run: npm run build -w ${{ env.WORKSPACE_NAME }}
      - run: npm run lint -w ${{ env.WORKSPACE_NAME }}
      - run: npm test -w packages/frontend
        env:
          CI: true
